[versions]
kotlin = "2.2.21"
jna = "5.16.0"
truth = "1.4.4"
mavenPublish = "0.34.0"

[libraries]
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
